### ISSUE TITLE
npm downgraded to 5.x if default version is 10.x

### ISSUE THREAD

**Issue by sdaicz** [heroku/heroku-buildpack-nodejs#1140]
**Describe the bug**
Now that the default npm version for node 20.7 is 10.1.0, if an npm version is not specified it will be incorrectly downgraded to 5.x

**To Reproduce**
1. Specify `"engines": { "node": "20.x" }` in your package.json file (note that `"npm"` is not specified)
2. Build your app on Heroku
3. In the build log you'll see something like:

       Downloading and installing node 20.7.0...
       Detected package-lock.json: defaulting npm to version 5.x.x
       Bootstrapping npm 5.x.x (replacing 10.1.0)...
       npm 5.10.0 installed
4. Your build will probably fail with some obscure error message later

**Versions (please complete the following information):**
 - Heroku Stack: `heroku-22`
 - Node Version: `20.7.0`
 - NPM Version: `10.1.0`
 - Buildpack Version: `heroku/nodejs v221`

**Additional context**
The issue originates from this line, which only looks at the first character of the default node version: https://github.com/heroku/heroku-buildpack-nodejs/blob/c14b37dbc032b97226cc52300f2d816dff1f29e5/lib/binaries.sh#L115

**Comment by davekaro** [comment]
Similarly, I noticed some new warnings present that are due to the same bug in the code.

```
 !     This version of npm (10.1.0) does not support package-lock.json. Please
       update your npm version in package.json.
       https://devcenter.heroku.com/articles/nodejs-support#specifying-an-npm-version
``` 

which comes from https://github.com/heroku/heroku-buildpack-nodejs/blob/c14b37dbc032b97226cc52300f2d816dff1f29e5/lib/failure.sh#L760.

I searched the [code](https://github.com/search?q=repo%3Aheroku%2Fheroku-buildpack-nodejs%20npm_version%3A0%3A1&type=code) and found it may also present a problem here https://github.com/heroku/heroku-buildpack-nodejs/blob/c14b37dbc032b97226cc52300f2d816dff1f29e5/lib/failure.sh#L748
