### ISSUE TITLE
prune-dev-dependencies fails consistently

### ISSUE THREAD

**Issue by mikepink** [heroku/heroku-buildpack-nodejs#1187]
**Describe the bug**
I'm working on upgrading our version of Node to 20.10.0 (from the previous LTS) and observed that our builds consistently failed during `yarn heroku prune`. Logs excerpts below contain more details but `Push rejected, failed to compile Node.js app.` is the only error message we receive with no further details on what broke or how I might fix it. We did not observe this behavior in Node 16 or Node 18.

**To Reproduce**
1. Update `engines` in `package.json` to `20.x`
2. Deploy test branch to Heroku
3. Observe `Push rejected, failed to compile Node.js app.` during `yarn heroku prune`.

**Versions (please complete the following information):**
 - Heroku Stack: `heroku-20` and `heroku-22`
 - Node Version: `20.10.0`
 - NPM or Yarn Version: `Yarn 3.2.4` and `Yarn 3.6.4`
 - Buildpack Version: [e.g. `heroku/nodejs@latest`]

**Additional context**
Build log excerpts below. I did find it curious that when running `Yarn 3.2.4`, I did find it curious that Heroku installed `Yarn 3.6.1` instead. Also, I have tried disabling pruning via `YARN2_SKIP_PRUNING`, however that pushes my app over the hard slug size limit.

```
-----> Building on the Heroku-20 stack

...

-----> Node.js app detected
2023-12-12 00:18:31        
2023-12-12 00:18:31 -----> Creating runtime environment
2023-12-12 00:18:31        
2023-12-12 00:18:31        NPM_CONFIG_LOGLEVEL=error
2023-12-12 00:18:31        USE_YARN_CACHE=true
2023-12-12 00:18:31        NODE_VERBOSE=false
2023-12-12 00:18:31        NODE_ENV=production
2023-12-12 00:18:31        NODE_MODULES_CACHE=true
2023-12-12 00:18:31        
2023-12-12 00:18:31 -----> Installing binaries
2023-12-12 00:18:31        engines.node (package.json):  20.x
2023-12-12 00:18:31        engines.npm (package.json):   unspecified (use default)
2023-12-12 00:18:31        engines.yarn (package.json):  3.2.4
2023-12-12 00:18:31        
2023-12-12 00:18:31        Resolving node version 20.x...
2023-12-12 00:18:32        Downloading and installing node 20.10.0...
2023-12-12 00:18:35        Using default npm version: 10.2.3
2023-12-12 00:18:35        Resolving yarn version 3.2.4...
2023-12-12 00:18:35        Downloading and installing yarn (3.2.4)
2023-12-12 00:18:36        Using yarn 3.6.1

...

2023-12-12 00:35:07 -----> Caching build
2023-12-12 00:35:07        - yarn cache
2023-12-12 00:35:09        
2023-12-12 00:35:09 -----> Pruning devDependencies
2023-12-12 00:35:09        Running 'yarn heroku prune'
2023-12-12 00:35:10        ➤ YN0000: ┌ Resolution step
...
2023-12-12 00:35:10        ➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
2023-12-12 00:35:10        ➤ YN0000: └ Completed in 0s 584ms
2023-12-12 00:35:10        ➤ YN0000: ┌ Fetch step
...
2023-12-12 00:35:11        ➤ YN0013: │ @babel/plugin-transform-arrow-functions@npm:7.22.5 can't be found in the cache and will be fetched from the remote registry
Node.js v20.10.0
 !     Push rejected, failed to compile Node.js app.
 !     Push failed
```

**Comment by colincasey** [comment]
Thanks for submitting this @mikepink. I will try to reproduce your issue though, since no other applications have reported issues with the Yarn pruning step, I wonder if it may be a specific dependency causing the issue.  Would you be able to share more details?

Also, regarding the detection & download of Yarn 3.2.4 but then Yarn 3.6.1 is used:
- v3.2.4 is downloaded and installed because that's what declared in `package.json` which is indicated by this output `engines.yarn (package.json):  3.2.4`
- v3.6.1 is likely what you have checked into your application's `.yarn/releases/` folder and referenced in `.yarnrc.yml` via the `yarnPath` configuration because that is typically how Yarn 2+ installs are configured

If that is accurate, you could drop the usage of `engines.yarn` in your `package.json`.  Or you could leave it in place as well since it isn't causing any harm.  The build will always download and install a Yarn binary (the default is 1.x).  The installed binary then delegates all commands to the actual version configured in your application (3.6.1).

**Comment by mikepink** [comment]
Thanks @colincasey - you're intuition was right re: yarn version. We have `.yarn/releases/yarn-3.6.1.cjs` in our `.yarnrc.yml`. 

I agree that this likely isn't a broad issue. I was hoping for more debug information from either `yarn heroku prune`, `yarn`, or the Heroku build dyno than what I'm seeing right now. The original logs doesn't have any more log lines beyond the final lines in the excerpt I shared.  Do you have any recommendations for what I can do to collect more debug information?

Here are relevant excerpts from our `package.json` in case it's helpful:
```
{
  "name": "mikepinkapp",
  "version": "0.0.1",
  "description": "mikepinkapp",
  "private": true,
  "scripts": {
    ...
    "heroku-postbuild": "./bash/heroku_postbuild.sh",
    ...
  },
  "repository": {
    "type": "git",
    "url": "..."
  },
  "engines": {
    "node": "20.x",
    "yarn": "3.2.4"
  },
  "optionalDependencies": {
    "fsevents": "2.3.2"
  },
  "dependencies": {
    "private-package-1": "git+https://github.com/*.git#cd54bdff3036982ffc207724da3b4d300d6dc5ae",
    "private-package-2": "https://github.com/*.git#015746541f51fac87f7288e08515192fd55cf064",
    "private-package-3": "github:*/*#82e95bc7453b4e8e0b8338396dd574abca06b82b",
    "public-package": "npm:public-package@latest",
    "vite": "4.4.7",
    "webpack": "^4.47.0",
    ...
  },
  "devDependencies": {
    "@babel/core": "^7.23.2",
    "@originjs/vite-plugin-commonjs": "^1.0.3",
    "eslint-plugin-mycompany": "link:./eslint-rules",
    ...
  },
  "resolutions": {
    "@types/react": "16.14.0",
    "@types/react-dom": "16.9.14"
  },
  "jest-junit": {
    ...
  },
  "peerDependencies": {
    "grpc-tools": "^1.11.2"
  },
  "packageManager": "yarn@3.6.1",
  "workspaces": [
    "bootstrap/"
  ]
}
```

**Comment by colincasey** [comment]
Nothing stands out to me in the `package.json`.  I've tried reproducing the issue and so far have not been successful.  

Something else I'm noticing is that the output you listed from `yarn heroku prune` seems to be cut off:
```
2023-12-12 00:35:09 -----> Pruning devDependencies
2023-12-12 00:35:09        Running 'yarn heroku prune'
2023-12-12 00:35:10        ➤ YN0000: ┌ Resolution step
...
2023-12-12 00:35:10        ➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
2023-12-12 00:35:10        ➤ YN0000: └ Completed in 0s 584ms
2023-12-12 00:35:10        ➤ YN0000: ┌ Fetch step
...
2023-12-12 00:35:11        ➤ YN0013: │ @babel/plugin-transform-arrow-functions@npm:7.22.5 can't be found in the cache and will be fetched from the remote registry
Node.js v20.10.0
 !     Push rejected, failed to compile Node.js app.
 !     Push failed
```

I would expect, in the case of an error, to see a message from one of the two following error handlers in the `prune` plugin:
- https://github.com/heroku/heroku-buildpack-nodejs/blob/main/yarn2-plugins/prune-dev-dependencies/src/index.ts#L37-L38
- https://github.com/heroku/heroku-buildpack-nodejs/blob/main/yarn2-plugins/prune-dev-dependencies/src/index.ts#L54-L55

@mikepink Could you try running the `prune` plugin locally against your repository to see if that produces more detail?  Here's how you use it locally:
- Download the compiled plugin script [here](https://github.com/heroku/heroku-buildpack-nodejs/blob/main/yarn2-plugins/prune-dev-dependencies/bundles/%40yarnpkg/plugin-prune-dev-dependencies.js)
- Run `yarn install` on your application
- Run `YARN_PLUGINS=/path/to/downloaded/plugin-prune-dev-dependencies.js yarn heroku prune` on your application

**Comment by mikepink** [comment]
I ran the prune plugin (after running `yarn install`) using Node 20.10.0 locally, and it successfully completed in ~9.7s. This leads me to think that the issue is probably the result of some cross-product between the Heroku build environment and the overall build process for my app. Unfortunately, that does make this more difficult to debug.

Feel free to close this out if needed. This likely isn't an issue with the plugin in isolation.

**Comment by colincasey** [comment]
Okay, that makes more sense. The truncated output seems to indicate an issue with Yarn but more evidence is needed.  

If the issue only shows up in the Heroku build environment, another thing you could do to investigate further is run this buildpack locally against your application. It requires a bit of setup but it may help with isolating the root cause:
- You need to have [Docker installed](https://www.docker.com/products/docker-desktop/)
- Copy your application code to a folder in [`test/fixtures`](https://github.com/heroku/heroku-buildpack-nodejs/tree/main/test/fixtures) (for example `test/fixtures/my-app`)
- Add the following code to [`test/run`](https://github.com/heroku/heroku-buildpack-nodejs/blob/main/test/run)
  ```bash
  testMyApp() {
    compile "my-app"
    cat $STD_OUT
    cat $STD_ERR
    assertCapturedSuccess
  }
  ```
- To test against `heroku-20`
  - modify [this line](https://github.com/heroku/heroku-buildpack-nodejs/blob/main/makefile#L31) so that it ends with `test/run -- testMyApp;`
  - run `make heroku-20-build`
- To test against `heroku-22`
  - modify [this line](https://github.com/heroku/heroku-buildpack-nodejs/blob/main/makefile#L26) so that it ends with `test/run -- testMyApp;`
  - run `make heroku-22-build`

The advantage of this is that you would have full control over both your application code as well as the buildpack code.

**Comment by mikepink** [comment]
Thanks @colincasey. Running the builldpack locally also completed successfully. 

One interesting data point - the issue we're observing consistently repros on vite@4.4.7. We upgraded vite to 4.4.9, 4.4.11, and 4.5.1 and did not observe the issue. The downside is that those builds consistently took ~10m longer than 4.4.7.

My best guess is that we're encountering the (disk or memory) limits of the Heroku build dynos. I can't verify that due to lack of visibility into their build environment, but I can't come up with a better explanation for what we've observed. Appreciate your time in helping me debug this.
