### ISSUE TITLE
Known to work with multi-buildpack?

### ISSUE THREAD

**Issue by anthonator** [heroku/heroku-buildpack-nodejs#134]
Is this buildpack known to work with the multi-buildpack? I have a ruby/nodejs combo and the nodejs buildpack seems to be overwriting the ruby buildpack. The Ruby version is wrong and the installed gems are gone when I run `ls` and `ruby -v` commands in a postinstall script.

My `.buildpacks`:

```
https://github.com/heroku/heroku-buildpack-ruby.git
https://github.com/heroku/heroku-buildpack-nodejs.git
```

My `Gemfile`:

``` ruby
source 'https://rubygems.org'

ruby '2.1.5'

gem 'sass', '~> 3.4.0'
```

**Comment by rdmurphy** [comment]
I'm having the same issue. I use the Ruby buildpack to install Sass with Ruby 2.1.5. Then, the Node buildpack takes over and installs Bower + Gulp, and tries to run the `gulp-ruby-sass` command. The call to Sass sees my Gemfile, and flips out because Ruby 1.9.2 is being run against it instead of 2.1.5.

This leads me to believe that the Node buildpack doesn't see what the Ruby buildpack established before it. Maybe a $PATH issue? May even be a problem on the Ruby buildpack side? I'm not well versed in how this system works, so I'm just guessing.

For what it's worth, I got it work by matching the version the Node buildpack tries to use (1.9.2) in my Gemfile, but that's a little flaky.

**Comment by hunterloftis** [comment]
I think @schneems may have a branch of the ruby buildpack that exports the ruby binaries so subsequent buildpacks can consume them.

**Comment by schneems** [comment]
Let me know if it works https://github.com/heroku/heroku-buildpack-ruby/pull/326

**Comment by anthonator** [comment]
@schneems I finally got a chance to try this on another project and it does indeed work now. Thanks!

**Comment by hunterloftis** [comment]
@anthonator awesome!
