### ISSUE TITLE
Provide hook for us to compile our app

### ISSUE THREAD

**Issue by ptarjan** [heroku/heroku-buildpack-nodejs#266]
Right now the hooks we have are `npm install` and then `npm start`. I need to compile my app (mostly `browserify`) and it takes ~2 minutes. If I put it as a `postinstall` step, then every developer on my team has to go through the prod-compile whenever they `npm install`. If I put it as a `npm prestart` then my app starts to compile but then dies with

```
2015-09-24T23:57:34.041984+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
```

So can I have a `npm compile` or something I can hook to?

**Comment by hunterloftis** [comment]
The 'scripts' field in package.json isn't part of the buildpack; it's part of the npm lifecycle scripts, and you can use any of the supported hooks:

- https://docs.npmjs.com/misc/scripts

I would recommend leaving client-side builds in `postinstall` since building the app is ostensibly part of installing it (and working on it). For installing new modules, `npm install --save --save-exact modulename` should do the trick (vs manually editing package.json and rerunning `npm install`).

However, if part of your team wants to be able to frequently run `npm install` but not trigger a `postinstall` script, one solution is to check the environment before browserifying. For instance, if NODE_ENV === 'production' then browserify.

**Comment by ptarjan** [comment]
Is there a specific `NODE_ENV` that this buildpack sets? In dev-mode I don't do the browserify (and instead use watchify since people will be changing files) so it is really just heroku that I need to run the prod step for.

**Comment by hunterloftis** [comment]
Yep, the buildpack sets `NODE_ENV=production` by default. It sounds like your setup will work pretty well (watchify in dev / browserify in prod).

**Comment by narwajea** [comment]
You could use the "heroku-postbuild" script instead of "postinstall" (see http://stackoverflow.com/questions/36223070/how-to-deploy-node-that-uses-webpack-to-heroku).
