### ISSUE TITLE
node and npm are re-downloaded and installed after every push

### ISSUE THREAD

**Issue by TheNotary** [heroku/heroku-buildpack-nodejs#306]
Hi all.  I'm noticing that node and npm are downloaded on every push of a node app.  https://github.com/heroku/heroku-buildpack-nodejs/blob/v90/lib/binaries.sh#L10-L26

I was at first feeling bad for me and my new ISP's bandwidth limit, but it looks like there's a proxy service getting hit pretty hard by this and eventually semver.io will have to pick up this load #300.  

Does this seem like an issue worth addressing?  I'm currently researching 12factor setups and build scripts in particular and could probably come up with a PR that checks `node -v` to see if an install is required (or check the container's /tmp dir for left overs or possibly something more intricate if working within buildscripts is more constrained than I'm hoping).

**Comment by hunterloftis** [comment]
Hi,

Builds are intentionally stateless. The exception to that rule is the cache. However, moving node to the cache would increase complexity but wouldn't speed things up (since the cache is on S3, and the node download from s3pository is also on S3).

The node installation tends to take between 1 and 5 seconds, so I wouldn't worry too much about download times.

I'm not sure I understand the concerns re: your ISPs bandwidth limit. Downloading node during a deployment is done from server-to-server and will not impact your personal bandwidth.

**Comment by TheNotary** [comment]
Thanks for the quick reply @hunterloftis!

This came up for me when working with a 'usually' offline dokku server a few feet from me.  Looks like the ideal fix for myself is to use a modified buildscript that downloads node from localhost.

**Comment by TheNotary** [comment]
Btw, @hunterloftis is that Scala app mentioned in #300 opensource?  If it can be detached from S3, it might be kinda nice to send towards dokku folks to add a cache layer.

**Comment by hunterloftis** [comment]
@TheNotary I believe you can also set `HTTPS_PROXY` as an environment variable to get curl to point elsewhere (like your local server).
