### ISSUE TITLE
npm fails to install dependencies

### ISSUE THREAD

**Issue by iyunusov** [heroku/heroku-buildpack-nodejs#333]
Below are two packages and I am trying to push my project to heroku with them, console saying that npm and node are installed on server but when I clone the project there is no node_modules directory in the project. 'bower install' in package.json saying bower is not found. When I remove 'bower install' no dependency is installed on server when pushed, though console writes them down as installed they're not installed on server when I open browser console.

package.json:
```
{
  "name": "meal-order",
  "version": "0.0.0",
  "description": "This is an app for ordering meal",
  "main": "gulpfile.js",
  "dependencies": {
    "angular": "^1.5.5",
    .....(other angular -libs)
    "express": "^4.14.0",
    "gulp": "^3.8.8",
    "gulp-connect": "^3.0.9",
    "ionicons": "^3.0.0",
    "protractor": "^3.3.0"
  },
  "devDependencies": {
      "bower": "1.7.7"
  },
  "engines": {
    "node": "^5.11.1",
    "npm": "^3.8.6"
  },
  "scripts": {
     "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node index.js",
    "postinstall": "bower install"
  },
```

bower.json:
````

    "dependencies": {
    "angular": "^1.5.5",
    .....(other angular -libs)
    "express": "^4.14.0",
    "gulp": "^3.8.8",
    "gulp-connect": "^3.0.9",
    "ionicons": "^3.0.0",
    "protractor": "^3.3.0"
    },
    "devDependencies": {},
    "main": "gulpfile.js",
    "license": "ISC",
    "moduleType": [
        "node"
    ],
```

.gitignore:
```

/node_modules/*
node_modules/*
node_modules
npm-debug.log
```

This is the error I get on console:
```
remote: -----> Restoring cache
remote:        Skipping cache restore (new runtime signature)
remote: 
remote: -----> Building dependencies
remote:        Installing node modules (package.json)
remote:        
remote:        > meal-order@0.0.0 postinstall /tmp/build_3ac183217c4c79ebe98cbb69eecb36de
remote:        > bower install
remote:        
remote:        sh: 1: bower: not found
remote:        
remote:        npm ERR! Linux 3.13.0-91-generic

```

**Comment by edmorley** [comment]
By default, the buildpack only installs packages listed in `dependencies`, not also those in `devDependencies` (since the latter are supposed to only be used for development, not in production:
https://devcenter.heroku.com/articles/nodejs-support#devdependencies

You'll need to either move the bower package to `dependencies`, or else run `heroku config:set NPM_CONFIG_PRODUCTION=false`, to install packages in `devdependencies` too. I'd strongly recommend the former, given the latter also sets `NODE_ENV=production` for lifecycle scripts and so has effects like [this](http://apmblog.dynatrace.com/2015/07/22/the-drastic-effects-of-omitting-node_env-in-your-express-js-applications/).

**Comment by hunterloftis** [comment]
Thanks @edmorley!

**Comment by iyunusov** [comment]
Moving `bower` to `dependencies` in package.json doesn't change anything, I am facing the same error again.

**Comment by hunterloftis** [comment]
@iyunusov, please open a support ticket (help.heroku.com) so I can look at your specific app. We haven't had any other reports of dependencies failing to install despite tens of thousands of installs since the issue was opened, so I'm fairly certain it's an app-specific issue rather than an issue with the buildpack.
