### ISSUE TITLE
Consider adding a pre-build hook

### ISSUE THREAD

**Issue by hunterloftis** [heroku/heroku-buildpack-nodejs#363]
This has been asked for a few times, and it would help resolve things like this:

https://twitter.com/ianwremmel/status/821426123745525761

The idea being that you could set up stuff before npm executes at all (instead of having to rely on something like a "preinstall" hook).

**Comment by ianwremmel** [comment]
full issue, not segmented into 140 character chunks. 

While the solution on the [npm blog](http://blog.npmjs.org/post/118393368555/deploying-with-npm-private-modules) for support private modules works, it makes local development inconvenient. 

npm makes authorized requests by reading a value out of `~/.npmrc`, which can be overridden by `./.npmrc`. With the solution described in the blobl, `npm install` is broken in the project directory unless the environment variable `NPM_TOKEN` is set. That's fine for cloud providers, but it's really a pain for local development. Ideally, npm would accept tokens from environment variables, but, barring that, @hunterloftis's solution of a pre-build hook would make it possible to write a `./.npmrc` only on heroku, rather than committing directly to the project directory.

**Comment by hunterloftis** [comment]
Aaand it looks like I already did this:

- https://github.com/heroku/heroku-buildpack-nodejs/blob/0387c21145e3390db792fd533c649aba40717dab/CHANGELOG.md#L23

Just add a "heroku-prebuild" script that echoes out your .npmrc.

**Comment by ianwremmel** [comment]
haha, awesome. Can you point me at any docs on how to register a hook?

**Comment by hunterloftis** [comment]
It's nothing heroku-specific, just a standard package.json script, eg:

```json
"scripts": {
  "heroku-prebuild": "echo 'do your thing here'"
}
```

**Comment by ianwremmel** [comment]
oh, gotcha. thanks!
