### ISSUE TITLE
Cache length.

### ISSUE THREAD

**Issue by gl2748** [heroku/heroku-buildpack-nodejs#400]
How long is the node_modules directory cached for?

**Comment by jmorrell** [comment]
Forever since it is saved in your application's slug. If you redeploy an application from years ago, it will use the `node_modules` cache from when it was built.

The cache gets invalidated and rebuilt any time you change versions of `npm`, `node`, or `yarn`: https://github.com/heroku/heroku-buildpack-nodejs/blob/master/lib/cache.sh#L4
