### ISSUE TITLE
Support "build" npm script

### ISSUE THREAD

**Issue by jmorrell** [heroku/heroku-buildpack-nodejs#479]
While we offer support for running build scripts using [`heroku-prebuild` and `heroku-postbuild`](https://devcenter.heroku.com/articles/nodejs-support#customizing-the-build-process) hooks, the community has coalesced around using `build` for build scripts. Many boilerplates don't work out of the box on Heroku due to not running `build` by default.

This change is likely to break existing applications but will benefit users overall. So we should provide good error messaging about the change and how to fix your build.

**Comment by jasonkarns** [comment]
I strongly  disagree with this statement: > the community has coalesced around using build for build scripts

npm itself specifies that `prepare` is the script to be run for building a node package. This is the script that is run when packing, when publishing, and when installing (both for git-deps and when cloning directly).

I think it would be a great step backwards and contrary to node tooling to propose a script that would require duplication for people who are following the npm recommended way of building packages.

**Comment by jasonkarns** [comment]
More specifically, a properly specified node package, when following npm's guidance will _automatically_ build the node package during install. So heroku should have to do nothing for building to take place.

**Comment by jmorrell** [comment]
> npm itself specifies that prepare is the script to be run for building a node package.

I respect the appeal to authority, but I don't think it holds very well here.

The crux of the issue is that the community as a whole doesn't follow that guide. Just about any boilerplate or starter project has a `build` script defined.

create-react-app: https://github.com/facebook/create-react-app/tree/next/packages/react-scripts/template#npm-run-build
ng-cli: https://github.com/angular/angular-cli/blob/master/package.json#L13
next.js: https://github.com/zeit/next.js/#setup
gatsby.js: https://www.gatsbyjs.org/docs/deploy-gatsby/#heroku

I cannot find any that specify using `prepare`.

Any user following those default guides needs to modify their app to work on Heroku. We should follow where the community has gone. As much as possible these projects should "just work" on Heroku, and this is a big reason they currently don't.

**Comment by jasonkarns** [comment]
> I respect the appeal to authority, but I don't think it holds very well here.

The intention here is to point out the behavior that npm and yarn provide out of the box when using `prepare` which will be lost when using a difference script.

Would there be a possibility to do one or the other as a fallback when one isn't provided?

I agree that the community itself hasn't coalesced around `prepare`. The reasons for this are obvious. `prepare` was only introduced in npm 4. "build" as a default predates prepare but quite a large margin. Indeed, the prevalence of `build` is why npm couldn't use build as the name for the script, because that would have retroactively added a lot of semantics and behavior to a script that already existed in the wild for a lot of repos.

But this is not to say that it's not the _correct_ script and that the community _won't_ coalesce around this script, given time and understanding. (Lots of inertia to fight against here.) There's a lot of OOTB functionality that is gained (or lost) by using (or not) the conventions that npm and yarn prescribe.

**Comment by Cryptophobia** [comment]
I think a potential fallback behaviour from `prepare` to `build` has potential for users. You can also notify them in the logs that `prepare` is the recommended way to build by npm, directly when the buildpack runs...

That being said, if `prepare` was introduced in npm4, then buildpack head in that direction.

**Comment by hunterloftis** [comment]
One of the buildpack's goals is to allow the widest set of applications possible to "just work" without further configuration. To that end, I don't think we can ignore the community consensus around "build" for projects like react, angular, and next.

Similarly, we can't ignore "heroku-postbuild" as we've asked many users to adopt that convention since before "build" became a theme.

So regardless of whether or not the buildpack automatically runs "prepare," it's going to need to try an array of possible build commands, rather than just one.

The thing that makes me hesitant of supporting "prepare" is a decision I made in a similar direction years ago (2014). In order to follow the documented goals of npm scripts, I recommended that folks use "postinstall" to build their apps. This seemed like a clean and simple solution at the time - after all, it's run automatically by npm after an installation. In the years that followed it became clear that the thing you want to do when installing locally on your development machine frequently isn't exactly the same thing you want when deploying to production... so people started using environment vars and all sorts of other things to overload that (run-by-npm-by-default) script to serve the multiple use cases that I forced them into.

**Comment by jmorrell** [comment]
Some prior art: Zeit.co also uses the `build` script, using `now-build` instead if it's present: https://zeit.co/docs/deployment-types/node#file-system-specifications

The change I would make would mirror that: `build` by default, `heroku-postbuild` if it's present.

**Comment by joshmanders** [comment]
I'd like to see it as @jmorrell suggested. `build` by default or `heroku-postbuild` if present.

**Comment by metakermit** [comment]
Another issue is that from what I understand Heroku won't install devDependencies, so the best substitute for now is to add to your *app.json*:

```
"scripts": {
  "heroku-postbuild":
    "npm install --only=dev --no-shrinkwrap && npm run build"
}
```

(I would also like to see heroku/nodejs support this sort of behaviour out of the box, because it's so common among frontend JS frameworks)

**Comment by jmorrell** [comment]
@metakermit Heroku does install `devDependencies` by default for the build step, then removes them with `npm prune` once it is completed. This was done in this PR: https://github.com/heroku/heroku-buildpack-nodejs/pull/519 last February

Your example here should work with:

```
"scripts": {
  "heroku-postbuild": "npm run build",
  ...
}
```

**Comment by jmorrell** [comment]
Closing in favor of https://github.com/heroku/heroku-buildpack-nodejs/issues/583
