### ISSUE TITLE
Increase Node memory default during builds

### ISSUE THREAD

**Issue by jmorrell** [heroku/heroku-buildpack-nodejs#549]
We've seen an increasing failures due to frontend build exceeding Node default 1.5GB memory limit during build. Heroku runs these builds on machines with 2.5GB of memory. For users on Node 8 and greater we can set `NODE_OPTIONS="--max_old_space_size=2560"` to increase this.

The drawback is that once users hit this new limit, there will be nothing they can do to get past it. The current limit currently serves as an early warning system that something might be wrong with your build before it gets too bad.

**Comment by harrybiddle** [comment]
We've hit this issue too and since we are relatively inexperienced with node it took us quite some time to find this solution.

In my opinion we should increase the limit by default so that builds succeed. If a build fails on an earlier version of Node then the user could be advised to upgrade node. 

This means we wouldn't have the early warning system we now have. However, I'd argue getting builds to pass first time is more important. If it's feasible to do, simply spitting out a warning message for memory-hogging builds could be a good early warning system?

**Comment by jmorrell** [comment]
> If it's feasible to do, simply spitting out a warning message for memory-hogging builds could be a good early warning system?

This is a fantastic suggesting @harrybiddle! I'll see if I can implement something like this
