### ISSUE TITLE
Bluemix node js build pack to support webm audio conversion

### ISSUE THREAD

**Issue by nimmialampatt** [heroku/heroku-buildpack-nodejs#562]
Even after adding ffmpeg to bluemix node js build pack(I tried this https://github.com/BlueChasm/nodejs-buildpack-ffmpeg), it doesn't support webm audio format conversion.Could anyone please suggest alternate ways to support this issue?

**Comment by jmorrell** [comment]
@nimmialampatt if you use the container stack beta, you can define apt packages in `heroku.yml` https://devcenter.heroku.com/articles/buildpack-builds-heroku-yml#installing-packages-from-apt

```
build:
  languages:
    - nodejs
  packages:
    - imagemagick
```

Otherwise you could use the official node buildpack alongside https://github.com/kontentcore/heroku-buildpack-ffmpeg
