### ISSUE TITLE
MERN Deployment Fails at the React Build Stage

### ISSUE THREAD

**Issue by StevenJBurns** [heroku/heroku-buildpack-nodejs#589]
I'm sure my experience level is a barrier to solving this on my own but here's what's going on. Locally, the app works without a hitch for both the Express server and the React client  The first several attempts at deploying the whole MERN project failed. Later that night and for about 12 hours after deployments were magically working! Not sure what I did to fix it at that point even after reviewing all my commits to functional point in time. The next afternoon the failures resumed and still continue.

I don't know what I'm looking for in the logs exactly.  Here's a [link to the whole repo](https://github.com/StevenJBurns/franchise-favorites) on GitHub.

Without forcing someone to look through all my code here are the highlights. This is the error I am seeing: 
`-----> Node.js app detected

       

-----> Creating runtime environment

       

       NPM_CONFIG_LOGLEVEL=error

       NODE_ENV=production

       NODE_MODULES_CACHE=false

       NODE_VERBOSE=false

       

-----> Installing binaries

       engines.node (package.json):  10.13.0

       engines.npm (package.json):   6.4.1

       

       Resolving node version 10.13.0...

       Downloading and installing node 10.13.0...

       npm 6.4.1 already installed with node

       

-----> Restoring cache

       Caching has been disabled because NODE_MODULES_CACHE=false

       

-----> Building dependencies

       Installing node modules (package.json + package-lock)

       added 83 packages from 51 contributors and audited 183 packages in 4.374s

       found 0 vulnerabilities

       

       Running heroku-postbuild

       

       > franchise-favorites@0.2.0 heroku-postbuild /tmp/build_931c9bf9c5525315b61d0b7ff269200f

       > NPM_CONFIG_PRODUCTION=false npm install --prefix client && npm run build --prefix client

       

       

       > @fortawesome/react-fontawesome@0.1.3 prepack /tmp/npmcache.hRaKx/_cacache/tmp/git-clone-cb3227e0

       > npm run dist

       

       

       > @fortawesome/react-fontawesome@0.1.3 dist /tmp/npmcache.hRaKx/_cacache/tmp/git-clone-cb3227e0

       > cross-env NODE_ENV=production npm run build

       

sh: 1: cross-env: not found

npm ERR! file sh

npm ERR! code ELIFECYCLE

npm ERR! errno ENOENT

npm ERR! syscall spawn

npm ERR! @fortawesome/react-fontawesome@0.1.3 dist: `cross-env NODE_ENV=production npm run build`

npm ERR! spawn ENOENT

npm ERR! 

npm ERR! Failed at the @fortawesome/react-fontawesome@0.1.3 dist script.

npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

npm ERR!     /tmp/npmcache.hRaKx/_logs/2018-11-15T06_25_43_641Z-debug.log

Unhandled rejection Error: premature close

    at PassThrough.onclose (/tmp/build_931c9bf9c5525315b61d0b7ff269200f/.heroku/node/lib/node_modules/npm/node_modules/end-of-stream/index.js:47:67)

    at PassThrough.emit (events.js:187:15)

    at emitCloseNT (internal/streams/destroy.js:59:8)

    at process._tickCallback (internal/process/next_tick.js:63:19)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:

npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:

npm ERR!     /tmp/npmcache.hRaKx/_logs/2018-11-15T06_26_03_296Z-debug.log

npm ERR! code ELIFECYCLE

npm ERR! errno 1

npm ERR! franchise-favorites@0.2.0 heroku-postbuild: `NPM_CONFIG_PRODUCTION=false npm install --prefix client && npm run build --prefix client`

npm ERR! Exit status 1

npm ERR! 

npm ERR! Failed at the franchise-favorites@0.2.0 heroku-postbuild script.

npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

npm ERR!     /tmp/npmcache.hRaKx/_logs/2018-11-15T06_26_03_334Z-debug.log

-----> Build failed

       

       We're sorry this build is failing! You can troubleshoot common issues here:

       https://devcenter.heroku.com/articles/troubleshooting-node-deploys

       

       If you're stuck, please submit a ticket so we can help:

       https://help.heroku.com/

       

       Love,

       Heroku

       

 !     Push rejected, failed to compile Node.js app.

 !     Push failed`

Here is my package.json for React client: 
`{
  "name": "franchise-favorites-react-client",
  "author": "Steven J Burns",
  "version": "0.2.0",
  "private": true,
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^1.2.8",
    "@fortawesome/free-brands-svg-icons": "^5.5.0",
    "@fortawesome/free-solid-svg-icons": "^5.5.0",
    "@fortawesome/react-fontawesome": "0.1.3",
    "react": "^16.6.3",
    "react-dom": "^16.6.3",
    "react-router-dom": "^4.3.1",
    "react-scripts": "^2.1.1"
  },
  "devDependencies": {
    "cross-env": "^5.2.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ],
  "proxy": "http://localhost:8192"
}
`

And finally here is the package.json at the root (Express server level):
`{
  "name": "franchise-favorites",
  "author": "Steven J Burns",
  "version": "0.2.0",
  "license": "ISC",
  "main": "server.js",
  "scripts": {
    "dev": "nodemon server.js",
    "start": "node server.js",
    "test": "echo \"Error: no test specified\" && exit 1",
    "heroku-postbuild": "NPM_CONFIG_PRODUCTION=false npm install --prefix client && npm run build --prefix client"
  },
  "dependencies": {
    "chalk": "^2.4.1",
    "dotenv": "^6.1.0",
    "express": "^4.16.4",
    "mongoose": "^5.3.12",
    "morgan": "^1.9.1",
    "serve-favicon": "^2.5.0"
  },
  "engines": {
    "node": "10.13.0",
    "npm": "6.4.1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/StevenJBurns/franchise-favorites.git"
  },
  "bugs": {
    "url": "https://github.com/StevenJBurns/franchise-favorites/issues"
  },
  "homepage": "https://github.com/StevenJBurns/franchise-favorites#readme",
  "keywords": []
}
`
I have tried so many iterations of "fixes" I found from similar problems I'm not sure which way is up at this point. But it all still works locally as I mentioned so I have been pressing forward on the whole project until a savior comes forward and educates me on this...

My only guess is that the culprits could be the cross-env package or the react-fontawesome package but that's just a stab in the dark.  Any and all help is appreciated.  I want to learn from this!

**Comment by edmorley** [comment]
Hi!

The key part of the error message is `sh: 1: cross-env: not found`, which means that cross-env was either not installed, or not on PATH. I see that cross-env is not listed in the root `package.json` (which is the one that this buildpack automatically installs), and instead is listed in `client/package.json`. 

However it looks like the root `package.json`'s `heroku-postbuild` script entry is meant to overcome that - but must not be working:

```js
 "heroku-postbuild": "NPM_CONFIG_PRODUCTION=false npm install --prefix client && npm run build --prefix client"
```

Trying this out locally with npm v6.1.0, I believe the issue is that `--prefix` means "put node_modules into this other subdirectory" (so in this case `client/node_modules`) rather than what I think was intended - "switch current working directory to the 'client' directory and npm install/build there". (Strangely https://stackoverflow.com/questions/37485787/how-to-run-npm-install-without-changing-working-directory would suggest `--prefix` did used to work like that in the past, even if it doesn't now.)

I would try manually changing the working directory in `heroku-postbuild` instead, ie:

```js
 "heroku-postbuild": "cd client && NPM_CONFIG_PRODUCTION=false npm install && npm run build"
```

**Comment by StevenJBurns** [comment]
No luck yet but I think we're on the right trail.  I tried  A) add cross-env to the server side and B) changed the client/package.json heroku-postbuild to what you suggested.

This is what I see now:  sh: 1: rollup: not found

Have you ever stared at a single line for 36 hours ready to throw your computer out the window?

And thanks Ed!  It is very much appreciated as asking for help is definitely a soft-skill I have not conquered yet but here we are at 2am...

**Comment by edmorley** [comment]
Ah so I think I know what the remaining issue is:
* the `@fortawesome/react-fontawesome` package has a `prepack` script in its [own package.json](https://github.com/FortAwesome/react-fontawesome/blob/147172c8824620c2daf1df49780ed1abb7f2a68a/package.json#L31)
* `prepack` script entries [are run](https://docs.npmjs.com/misc/scripts) "before a tarball is packed (on npm pack, npm publish, and when installing git dependencies)"
* the `@fortawesome/react-fontawesome` entry in `client/package-lock.json` is referencing the package using a GitHub revision rather than NPM ([see here](https://github.com/StevenJBurns/franchise-favorites/blob/64f56e5eb019731d15db042aea9562edaa2934b1/client/package-lock.json#L886-L893))
* as such when `npm install` for the client subdirectory runs during `heroku-postbuild`, it's running `@fortawesome/react-fontawesome`'s `prepack` step (since it's a git install), which is trying to generate a `react-fontawesome` build - which requires a number of other packages such as `cross-env` and `rollup`
* however these dependencies are never not automatically installed, since they are `devDependencies` of `@fortawesome/react-fontawesome` rather than dependencies (which is the right thing IMO), but npm doesn't install them automatically at present due to npm/npm#19564

In short, it seems that `@fortawesome/react-fontawesome` is just not compatible with installing from GitHub without additional workarounds, due to the npm issue npm/npm#19564.

Presuming you're ok with using the latest published version of `@fortawesome/react-fontawesome` (rather than a specific revision from their GitHub repo), I would remove the `@fortawesome/react-fontawesome` entry from `client/package-lock.json` and then run `npm install` locally to regenerate it without the GitHub references. (Or alternatively delete `client/package-lock.json` entirely to force the refresh of all dependencies; often useful to do this periodically to force updates of transitive subdependencies.) This will make `npm install` complete without needing to run the "prepack" step at all.

After that, you should be able to remove all `cross-env` references from `package.json` and `client/package.json`, since they don't appear to be needed by your project itself.

**Comment by StevenJBurns** [comment]
Thanks for all your help again Ed!  I didn't know this was a thing but my suspicions were raised early on when I added react-fontawesome to the mix because I saw this line in the client/package.json:     

"@fortawesome/react-fontawesome": "github:fortawesome/react-fontawesome"

It didn't sit well with me so I wandered over to NPM, grabbed the ^0.1.3 reference and forced it in.

I understand from a 20,000 foot view now what you explained above, details will be resolved as I learn more I suppose.

I'm going to try what you recommended and I'll let you know how it pans out.  What I can't understand is why for several deployments over 12 hours it all worked.  In fact I'm certain even the fontawesome components were behaving as well on those first few deploys.

I'm going to purge the package-lock.json and see how this goes.  It's already super late here so I may not report my finding until I wake up from this coding stupor.

Thank you again!

**Comment by StevenJBurns** [comment]
OK, I got it working but it felt like the hackiest hack...

So I did what you recommended, removed all the devDependencies that I tried to install manually, killed the package-lock.json for both server and client (because why not and it made sense after you explained it). ran npm i for both server and client to refresh the package-lock files...

Something interesting happened after forcing the react-fontawesome to ^0.1.3 versus letting it default to github:fortawesome/react-fontawesome... inside the package-lock it was still using the resolved reference to GitHub.

So I went sleuthing in https://registry.npmjs.org/ since 99.9% of the packages had a resolve property that pointed to NPM vs GitHub.  I fished around here [https://registry.npmjs.org/@fortawesome/react-fontawesome](https://registry.npmjs.org/@fortawesome/react-fontawesome) and found the 0.1.3 entries which gave me the .tgz link and the integrity keys... I plugged these into package-lock, pushed to GitHub and deployed from Heroku.  Working app!

I know this isn't how it should be.  Please tell me you've seen hack-ier in your experience to justify two days of pain!  Along the way I found issues about this being partly a bug in NPM and my guess the Font Awesome author not updating the registry as it's probably still a relatively new push to v5 of the whole Font Awesome ecosystem?

I appreciate you looking at this and pointing me in the right direction and I'm honored to have a Mozilla big wig reach out to me so fast.

**Comment by siddhantvirus** [comment]
When I am using auto-deployment on Heroku, cd client doesn't seem to work, could someone help me out with that?

**Comment by Stephenlaye2** [comment]
The  "heroku-postbuild": "cd client && NPM_CONFIG_PRODUCTION=false npm install && npm run build" works like charm for me. Thanks.
