### ISSUE TITLE
Should `NODE_ENV` be set by the buildpack?

### ISSUE THREAD

**Issue by zeke** [heroku/heroku-buildpack-nodejs#60]
As @aseemk notes on the [Heroku Node forum](https://discussion.heroku.com/t/the-official-node-js-buildpack-is-going-on-a-diet/100/33):

> This might not be new to the diet buildpack, but I just noticed that the Node docs no longer say you guys set NODE_ENV=production. Is that right? If so, may I ask why the change?

Dev Center has [two articles](https://devcenter.heroku.com/search/NODE_ENV) that reference NODE_ENV=production, one about Express caching and the other a sample .profile.d. script.

Dare I ask, should `NODE_ENV` be set automatically by the buildpack? `PATH` is currently the only environment variable it touches.

cc @ddollar @dpiddy @jclem @mojodna @ryanbrainard @rwdaigle @friism

**Comment by NathanJang** [comment]
Is this still true? #77's discussions says it was rolled back.

**Comment by hunterloftis** [comment]
@NathanJang no longer true; this is the current default env: https://github.com/heroku/heroku-buildpack-nodejs/blob/aeac9d6e019c2f6df88968432c3a2e92481cf4a6/lib/environment.sh#L1-L5

However, keep in mind that when setting `NPM_CONFIG_PRODUCTION=true`, npm will set `NODE_ENV=production` for the subshells it spawns for things like `postinstall` scripts.

**Comment by aseemk** [comment]
That's disappointing to hear. Could the sane `NODE_ENV=production` default be brought back, but in the right way this time so that it *does* get overridden by `heroku config:set NODE_ENV=...`?

Thanks guys!

**Comment by aseemk** [comment]
(I'm not able to re-open this issue.)

**Comment by hunterloftis** [comment]
@aseemk users use heroku apps for all sorts of deployments (production, staging, automatic github branch testing). During the build, we set `NPM_CONFIG_PRODUCTION=true` by default to minimize build times, but other than that I'd like to leave environment settings to the user - especially given the volume of tickets we get from users confused by the env we currently set.

**Comment by NathanJang** [comment]
@hunterloftis: in my situation I need `NPM_CONFIG_PRODUCTION=false` because I need devDependencies to be installed, but I also need a simple way to check if the app is currently deployed in production (on Heroku) rather than in development.

**Comment by NathanJang** [comment]
I was confused because I was expecting it to be set for me based on #77 and this issue. Could the title/top post be edited so it's clearer?

**Comment by hunterloftis** [comment]
@NathanJang, you can just `heroku config:set NODE_ENV=production`. For example:

```
$ NODE_ENV=production NPM_CONFIG_PRODUCTION=false npm install

> time@0.11.3 install /Users/hloftis/test/express/node_modules/time
> node-gyp rebuild

  CXX(target) Release/obj.target/time/src/time.o
  SOLINK_MODULE(target) Release/time.node
  SOLINK_MODULE(target) Release/time.node: Finished

> express@0.0.0 postinstall /Users/hloftis/test/express
> echo NODE_ENV=$NODE_ENV

NODE_ENV=production
```

**Comment by NathanJang** [comment]
@hunterloftis Yes I know; I'm just saying I was confused by being led to this method by StackOverflow, finding this issue, but not seeing it set for me. It just wasn't clear from the comments that it's no longer the case. Thanks for all your help! :joy:

**Comment by aseemk** [comment]
@hunterloftis: I hear you. And I sympathize that this may be a breaking change (if customers rely on `NODE_ENV` not being set). I'll leave it in your hands, but I just want to toss out one parting thought:

Consider that *not* setting `NODE_ENV` by default *is* having an opinion: that by default, Node apps on Heroku should *not* cache Express views, *not* cache Browserify/Webpack bundles, *not* cache i18n strings, etc.

(Those aren't trivial things btw. In our app, we timed uncached Express view rendering at 50ms. And our template engine used to do file reads synchronously (that has since been fixed), which means that Node was locked for those 50ms!)

Heroku certainly does have an opinion on best practices by default. H12 timeouts are a perfect example: arguably unnecessary for Node (given [this rationale](http://engineering.heroku.com/blogs/2014-12-05-timeout-quickly/)), but it's a best practice. Same with everything in 12 Factor.

So... food for thought. Thanks, and good luck. =)

**Comment by aseemk** [comment]
Funny coincidence, 10 mins after posting this, I was browsing Twitter and saw this tweet/link:

> The Effects of Omitting NODE_ENV in Your Express.js Apps: http://apmblog.dynatrace.com/2015/07/22/the-drastic-effects-of-omitting-node_env-in-your-express-js-applications/

https://twitter.com/JavaScriptDaily/status/624217744574128128

**Comment by hunterloftis** [comment]
@aseemk thanks for the link. I generally share the opinion of [12factor.net](http://12factor.net/config):

> In a twelve-factor app, env vars are granular controls, each fully orthogonal to other env vars. They are never grouped together as “environments”, but instead are independently managed for each deploy. This is a model that scales up smoothly as the app naturally expands into more deploys over its lifetime.

A better practice is to explicitly set [view cache](http://expressjs.com/4x/api.html#app.settings.table) on express instead of implicitly using `NODE_ENV`. Similarly, for i18n, you should explicitly set [devMode](https://github.com/jeresig/i18n-node-2#devmode).

That said, I just did a quick spot check for `NODE_ENV` on the last 20 node builds. Six had `NODE_ENV` (or some other config, eg `VIEW_CACHE`) set while **fourteen left it undefined**. So, it does look like we're doing a disservice to non-expert users who aren't aware of their configuration options. Setting `NODE_ENV=production` by default will give such users a speed boost, while experts will be using explicit mechanisms anyway and will be minimally affected.

The problem with `.profile.d` scripts is, if you use them for output, they're super chatty (as evidenced by the `WEB_CONCURRENCY` stuff that I'm going to mute). However, if you don't show what `.profile.d` is doing, monkeying with the env can lead to confusion and frustration. I'll work up a PR and we can find a good mechanism. @aseemk @NathanJang, you volunteering to be beta testers? ;)

**Comment by aseemk** [comment]
Just to clarify my opinion, I'm not at all suggesting to use `NODE_ENV` to name different environments. We set `NODE_ENV` to `production` on every single one of our Heroku apps: production, staging, development, testing. We do not use `NODE_ENV` to identify environments — we use granular configs, as recommended by 12 Factor (and I agree). The reality is simply that `NODE_ENV` is looked at, and things are optimized when it's set to `production`, by many different modules. So I see it as "must set to `production` everywhere except local development, as a Node.js best practice".

(You're right that we could be explicit about those optimizations. Alas, we take advantage of the `NODE_ENV=production` convenience.)

Happy to help beta test as needed. Good luck. =)

P.S. I don't find build noise to be an issue, FWIW. The bulk of the noise is from npm, right? And that can be improved / is improving (I don't remember exactly) with recent versions of npm?

**Comment by hunterloftis** [comment]
Feature is in master; I'll leave it there for a while before publishing the official buildkit so we can work out any issues.

To test:

```
heroku buildpacks:clear
heroku buildpacks:set https://github.com/heroku/heroku-buildpack-nodejs
```

**Comment by aseemk** [comment]
Nice! Thanks @hunterloftis.

**Comment by devpascoe** [comment]
i'm with @aseemk 
i just added an env var POST_INSTALL_ENV = staging
then in package.json
scripts: {
"postinstall": "sh postinstall.sh"
}

and in postinstall.sh

#!/bin/bash
echo "--- PostInstall script ---"
if [ "$POST_INSTALL_ENV" = "production" ]
    echo "--- On Production ---"
then
    echo "--- On Production ---"
else
    echo "--- On Staging ---"
fi

**Comment by yagudaev** [comment]
We actually ended up creating a

```bash
NODE_ENV=production
BROWSER_ENV=staging
```
On heroku. We expose it as 

```js
window.BROWSER_ENV
// on node
process.env.BROWSER_ENV
```

**Comment by narwajea** [comment]
How do you expose it ?
