### ISSUE TITLE
Yarn cache does not work by default

### ISSUE THREAD

**Issue by jwickens** [heroku/heroku-buildpack-nodejs#665]
Hi, the docs 

https://devcenter.heroku.com/changelog-items/1082
https://devcenter.heroku.com/articles/nodejs-support#cache-behavior

suggests that yarn caching works by default. My builds consistently showed however that only node_modules was being cached, which is insufficient for yarn workspaces and also inconsistent with what the docs seems to specify above.

I tried setting cacheDirectory to the output of `heroku run yarn cache dir` but alas no avail.

After much digging I found out the buildpack sets the yarn cache dir to a temporary location:
https://github.com/heroku/heroku-buildpack-nodejs/pull/459

I tried working around this by having the following in package.json:

```
    "heroku-prebuild": "export YARN_CACHE_FOLDER=/app/.cache/yarn/v4"
```

But this did not help the problem. 

What would really help would have been the following PR which was never merged:
https://github.com/heroku/heroku-buildpack-nodejs/pull/615

**Comment by jtushman** [comment]
@jwikens. I am running into this too. Did you find a workaround?

**Comment by jwickens** [comment]
No unfortunately not, just living with ~70s install times about a 1/4 of the time of the entire build.

**Comment by jtushman** [comment]
I submitted a ticket -- we will see what they say.  But I think I am going to try to move to lerna/npm and see how that feels to me.

**Comment by jmorrell** [comment]
I'm working on an A/B test for caching the yarn cache instead of `node_modules` to see what the impact is there. I will also check that against caching all of the `workspace` `node_modules` directories, but this exploration will take time.

In the meantime, the biggest thing you can do would be to cache the workspace `node_modules` directories yourselves by adding a `cacheDirectories` configuration to `package.json`. https://devcenter.heroku.com/articles/nodejs-support#custom-caching

```
"cacheDirectories": ["client/node_modules", "server/node_modules"]
```

I don't think you can set the yarn cache directory to be cached yourself without significant hackery due to the build directory being a random temporary directory.

**Comment by jtushman** [comment]
Thanks @jmorrell !

I commented on a similar thread else where:

But I have tried adding that "cacheDirectories" settings and it does not seem to be picking those up.

My setup:

```
➜ heroku buildpacks
=== quala-success Buildpack URLs
1. https://github.com/timanovsky/subdir-heroku-buildpack
2. heroku/nodejs
```

My package strucuture:
```
app
    client/
    backend/      (a yarn workspace)
        package.json
        Procfile
        utils/
        data/
        server/
        cli/
```

Procfile:
```
web: yarn workspace server start
```

backend/package.json
```
  "workspaces": [
    "cli",
    "data",
    "server",
    "utils"
  ],
  "cacheDirectories": [
    "node_modules",
    "backend/node_modules"
  ],
  "scripts": {
    "heroku-postbuild": "yarn workspace utils build && yarn workspace data build  && yarn workspace server build && yarn workspace cli build"
  },
  "engines": {
    "node": "10.16.0",
    "yarn": "1.17.3"
  },
```

Everything works -- except the node_module caching (which I would LOVE to get working)

I think you are an heroku employee -- happy to give you access to my repo.  I think the setup (while a little advanced) I have is not that uncommon.

**Comment by breathe** [comment]
Hi @jtushman — I’m not a heroku employee or as knowledgeable about this as Jeremy — but I think the heroku node buildpack will only process the cacheDirectories parameter from a ‘package.json’ file in the repository root.

I think you could place a pretty minimal package.json file in your project root and get this working ...

Something like
‘’’
{
  private: true,
  cacheDirectories: [
    “client/node_modules”,
     “backend/node_modules”,
      “backend/cli/node_modules”,
      “backend/data/node_modules”
     ...
    ]
}
‘’’
 
You’d just have that top level package.json for specifying cacheDirectories in a place that the heroku node buildpack would find it ...

I do something similar to your project however I have the root package.json as the root of the yarn workspace — not sure if you could do that as well by making the root package.json the root of your workspace and adding the client package to the workspace ...? if that worked seems like it would be cleaner as you could remove heroku-postbuild npm task and just have one yarn install to get all the dependencies for front-end/backend ...

**Comment by jtushman** [comment]
Thanks @breathe !

I actually have the cacheDirectories setting in the root as well (just incase that was the case) -- and still no avail for me.

The reason why I separate the client and backend is the client(a react app) is like 100MB once compressed.  So i would like to avoid having that in the server slug.

**Comment by jmorrell** [comment]
@jtushman I suspect the issues there probably stem from using the `subdir-heroku-buildpack` in conjunction with the Node buildpack, but I will take a look at your ticket and get back to you.

> the heroku node buildpack will only process the cacheDirectories parameter from a ‘package.json’ file in the repository root.

This is correct, though I'm not certain how the subdir buildpack would affect this.

**Comment by jmorrell** [comment]
The subdir buildpack effectively deletes everything except for the subdirectory and then moves it to the root build directory:

something like:
```
$ mv backend/* .
```

This means that:

- the root `package.json` does not exist by the time the Node buildpack is invoked
- the  cache directory `“backend/node_modules”` isn't correct because that directory is now at `./node_modules` with `“backend/cli/node_modules”` at `./cli/node_modules`

If these things seem unintuitive, I agree :\

**Comment by jmorrell** [comment]
I've merged a PR that adds a feature that swaps `node_modules` caching for caching the yarn native cache: https://github.com/heroku/heroku-buildpack-nodejs/pull/691

It's not currently rolled out to anyone, and I would like some feedback from people here if possible. You can opt-in to the feature, by creating a `heroku-buildpack-features` file at the root of  your application with the following contents:

```
cache-native-yarn-cache=true
```

or as a one-liner by running this in the root directory: 

```
echo "cache-native-yarn-cache=true" > heroku-buildpack-features
```

You will see `yarn cache` instead of `node_modules` in the caching sections of the log

**Comment by jwickens** [comment]
Thanks for the fix @jmorrell I'm happy to confirm that the yarn install step takes half the time now.

**Comment by dpikt** [comment]
I'm running into an issue with build caching that I think is related to this. I've got an app that is running `yarn cache` as the cache script instead of caching `node_modules` like my other apps. I didn't change any configuration for that, so perhaps in the 50% AB test group? Either way, it seems to be breaking caching and yarn runs fully each time the app builds (adds about 2 mins to build time). Do I need to tweak something to get my lockfile to work with this new caching method?

Also, I tried reverting to node modules caching via `"cacheDirectories"` but that didn't seem to make a difference.

**Comment by jmorrell** [comment]
> I've got an app that is running `yarn cache` as the cache script

@dpikt I'm not sure I understand what this means. Could you elaborate or give an example of the config you're using?

**Comment by dpikt** [comment]
Sure thing! Here's the truncated logs from a fresh review app: https://pastebin.com/raw/mSF7udy3.
As you can see, it's running 
```
-----> Caching build
       -  yarn cache
```
after the build. For other node apps of mine, that step just says 
```
-----> Caching build
       - node_modules
```
Could `NPM _CONFIG_PRODUCTION` be the culprit? Let me know if there's other info that could help.

**Comment by Merott** [comment]
@jmorrell any updates on this?

It appears that `cache-native-yarn-cache` has been [rolled out to everyone](https://github.com/heroku/heroku-buildpack-nodejs/commit/1e51050bb9ecbba7572ac2772002c6259062dad8#diff-9f034b63948763d489f944319c2eb3de) although I find the build to be still pretty slow.

**Comment by danielleadams** [comment]
@Merott This has been rolled out. If you're seeing that your build is slow - is it specifically at the yarn install/prune steps? Can you give more information? (If it's not related to yarn cache, preferably in a separate Issue or [support ticket](https://help.heroku.com/))

We found that overall builds did get faster, so I'd like to learn more about what you're seeing.

**Comment by danielleadams** [comment]
This feature has been rolled out 100% of builds: https://github.com/heroku/heroku-buildpack-nodejs/pull/758

If you'd like to manage using yarn caching, you can add a file to the root of your application called `heroku-buildpack-features`.

To opt in, the file should contain:
```
cache-native-yarn-cache=true
```

To opt out, the file should contain:
```
cache-native-yarn-cache=false
```

Keeping this issue open for now for anyone to report degraded performance, but I will close this in another couple weeks. If I see a significant number of builds that have turned this off, then I'll move the opt in/out file to an environment variable.

**Comment by danielleadams** [comment]
Finalized in v173: https://github.com/heroku/heroku-buildpack-nodejs/blob/master/CHANGELOG.md#v173-2020-07-16
