### ISSUE TITLE
Make pnpm an option (as well as the existing npm, yarn options)

### ISSUE THREAD

**Issue by timlesallen** [heroku/heroku-buildpack-nodejs#688]
How hard would this be?  Can anyone see any major obstacles?  I might be willing to have a crack at it.

**Comment by jmorrell** [comment]
I don't see any reason we couldn't do this. Could you speak to how you'd be served by having `pnpm` available? It's low usage has meant that this hasn't been a priority.

re: implementation

Right now, we have a pretty simple system. [If `yarn.lock` is present](https://github.com/heroku/heroku-buildpack-nodejs/blob/master/bin/compile#L92), we use `yarn`, otherwise `npm`. Adding another option means we'd have to complicate that somewhat, but we already fail if [multiple lockfiles are present](https://github.com/heroku/heroku-buildpack-nodejs/blob/master/bin/compile#L105).

Here we could check to see if `pnpm-lock.yaml` is present, and then default to `pnpm` if no other lockfiles are included.

`pnpm` could be bootstrapped by installing with the version of npm that came with the Node binary in the same way that `npm` is today: https://github.com/heroku/heroku-buildpack-nodejs/blob/master/lib/binaries.sh#L114

If I understand the global store concept correctly, you'd also need to make sure that was configured to exist within the `/app` directory that gets bundled into the slug, otherwise the packages would not be present at runtime.

**Comment by jamesarosen** [comment]
We'd love this too. We'd like to use `pnpm` for a few reasons:

1. It's generally faster than `npm` or `yarn`.
2. It has great monorepo workspace support. `yarn` does too, but `npm` does not.
3. It uses less disk space for developers.

Our team is hesitant to switch even our non-Heroku projects over to `pnpm` since Heroku can only do `npm` and `yarn` and we try to keep tooling consistent across projects.

**Comment by danielleadams** [comment]
Yarn 2 is supported on Heroku now, and we will be continuing to add support for it.

@timlesallen @jamesarosen Yarn 2 supports monorepos, [is comparably fast to pnpm](https://github.com/pnpm/benchmarks-of-javascript-package-managers/tree/mael/yarn2#benchmarks-of-javascript-package-managers), and also uses less disk space because of the compressed dependencies - would this be a suitable solutions given what you're looking for?

**Comment by jamesarosen** [comment]
One of the other key benefits of pnpm is that it supports fairly sophisticated monorepo commands like `pnpm test --filter ...[origin/main]`, which runs `test` on all packages that have changed since the head of `origin/main`, plus all their dependents. It does look like Yarn 2 has better integration with Lerna, so perhaps `lerna changed` could work for this.

**Comment by creepinson** [comment]
I would really love to see pnpm as well, I had to change my scripts to use normal npm.. Also, when installing node_modules this would make a difference as well.

**Comment by zcserei** [comment]
+1, I would love to see this as well and I unknowingly assume that the solution laid out by @jmorrell would probably work fine.

**Comment by danielleadams** [comment]
Thanks for the feedback here - I'll keep this open for now, but it's likely Heroku won't get to implementing this in the near future.

**Comment by perkinss** [comment]
Welp, it looks like the latest version of Yarn is causing issues in my build environment.  Heroku upgraded Yarn, so my rails tests were passing locally but failing on Heroku till I upgraded Yarn.  After switching to use PNPM locally the errors are fixed.  

So, it would be really great!!! if this could be allowed as soon as possible.

**Comment by danielleadams** [comment]
@perkinss you can still use the old version of Yarn (`1.x`) or, as you pointed out, npm. Seems like you need to lock your Yarn version: https://devcenter.heroku.com/articles/nodejs-support#specifying-a-yarn-version

**Comment by perkinss** [comment]
@danielleadams, thanks, good point.  Still would prefer to go to pnpm

**Comment by wmakley** [comment]
Love pnpm and would love to use it with Heroku. Yarn and npm are slow and wasteful for development purposes.

**Comment by seahindeniz** [comment]
Well, pnpm is also an officially supported package manager in [VSCode 1.47](https://code.visualstudio.com/updates/v1_47#_tasks) and GitHub Actions also supports running pnpm workflows, so I would also appreciate having it on Heroku as well.

**Comment by gaggle** [comment]
> Thanks for the feedback here - I'll keep this open for now, but it's likely Heroku won't get to implementing this in the near future.
@danielleadams would you accept PRs that adds that support? Or are you saying here you recommend a custom build pack to fill this niche?

**Comment by gaggle** [comment]
> > Thanks for the feedback here - I'll keep this open for now, but it's likely Heroku won't get to implementing this in the near future.
> 
> @danielleadams would you accept PRs that adds that support? Or are you saying here you recommend a custom build pack to fill this niche?

Oh, not sure @danielleadams works at Heroku anymore 😬 Sorry if I'm mis-tagging.

**Comment by danielleadams** [comment]
I don't. Sorry!

**Comment by marcmarina** [comment]
Is there an update on this?

**Comment by joshwlewis** [comment]
> would you accept PRs that adds that support? Or are you saying here you recommend a custom build pack to fill this niche?

At this point, I'd recommend a custom buildpack. Accepting a PR that adds support is just the start of a support story; there's docs, support, and maintenance overhead going forward. If someone were to create a custom buildpack and it gained a fair bit of traction, it'd be much easier for us to justify first party support for it.

**Comment by MarvinRudolph** [comment]
> > would you accept PRs that adds that support? Or are you saying here you recommend a custom build pack to fill this niche?
> 
> 
> 
> At this point, I'd recommend a custom buildpack. Accepting a PR that adds support is just the start of a support story; there's docs, support, and maintenance overhead going forward. If someone were to create a custom buildpack and it gained a fair bit of traction, it'd be much easier for us to justify first party support for it.
> 
> 
> 
> 

So does this mean there isn't planned any first party support for pnpm yet in the next months? 
My main reason for the pnpm support in the buildpack is that Digitalocean's app platform relies on it which also makes the use of pnpm there impossible. 😕

**Comment by joshwlewis** [comment]
> So does this mean there isn't planned any first party support for pnpm yet in the next months?

No planned support for `pnpm` from the Heroku side. I can't comment on support from other platforms. Again, if a custom pnpm buildpack were to gain traction, we'd reconsider official support.

**Comment by productdevbook** [comment]
pnpm support please

**Comment by MarvinRudolph** [comment]
> pnpm support please

Try render.com

**Comment by loeffel-io** [comment]
+1

**Comment by jasonkuhrt** [comment]
PnPM now ships with Node. Anything shipping with Node should be supported by this buildpack. See [corepack](https://nodejs.org/api/corepack.html) for more details.

**Comment by chinnichaitanya** [comment]
Very much looking forward to this feature! Getting difficult to deploy with App ecosystem.

**Comment by ScreamZ** [comment]
@danielleadams Please can you do something about it ?

> PnPM now ships with Node. Anything shipping with Node should be supported by this buildpack. See [corepack](https://nodejs.org/api/corepack.html) for more details.

**Comment by danielleadams** [comment]
> @danielleadams Please can you do something about it ?
I don't work at Heroku anymore, so I would suggest reaching out to the current employee/contributor.

**Comment by ScreamZ** [comment]
@hunterloftis @jmorrell @ddollar 
Maybe you can ? ;)

> PnPM now ships with Node. Anything shipping with Node should be supported by this buildpack. See [corepack](https://nodejs.org/api/corepack.html) for more details.

**Comment by fkrauthan** [comment]
Is there any update on this? I started migrating all my projects to pnpm and would love to easily deploy them.

**Comment by ScreamZ** [comment]
@fkrauthan I ended up making my own dockerFile for digitalOcean instead of using this buildpack, I guess you could achieve the same behavior with Heroku

**Comment by caleb531** [comment]
@ScreamZ Would you be able to share your Dockerfile? I am running into this same issue with my pnpm Node project on DigitalOcean App Platform.

**Comment by ScreamZ** [comment]
> @ScreamZ Would you be able to share your Dockerfile? I am running into this same issue with my pnpm Node project on DigitalOcean App Platform.

Wrote an article about it : https://medium.com/coding-spark/a-digitalocean-configuration-to-deploy-pnpm-based-backend-applications-f6d407a27206?sk=2563b0ac6350fd29aa33da224ee63bed

**Comment by caleb531** [comment]
@ScreamZ Got it, thank you! I was actually able to write a Dockerfile of my own (with the help of someone from DigitalOcean Support):

```dockerfile
# This Dockerfile is necessary because DigitalOcean's node buildpack does not
# support pnpm (only npm/yarn); to work around this, we must containerize the
# application ourselves, which allows us to install pnpm without issue

# Base image
FROM node:16-alpine
RUN apk update && apk add --no-cache libc6-compat
RUN corepack enable && corepack prepare pnpm@latest --activate

# Set up project
WORKDIR /usr/app
COPY package.json pnpm-lock.yaml ./
RUN pnpm install
COPY ./ ./
RUN pnpm build

# Start server
EXPOSE 8080
ENV NODE_ENV production
CMD ["pnpm", "start"]
```

Since I am hosting my app on DigitalOcean's App Platform, I also needed to make sure I referenced my Dockerfile in my DO app spec (via the `dockerfile_path` field):

```yaml
# app.yml
...
services:
- dockerfile_path: Dockerfile
  ...
```

**Comment by its-monotype** [comment]
@cable So the only option to use pnpm is not to use Heroku?)

**Comment by MariuzM** [comment]
Jesus christ heroku team... you see people want pnpm, is it really that hard to support it?

**Comment by ScreamZ** [comment]
Or use a dockerfile custom

**Comment by baked-dev** [comment]
good to know that this is not planned, means we will have to make a plan to move away from heroku

**Comment by TheSecurityDev** [comment]
You can use https://github.com/unfold/heroku-buildpack-pnpm, or my fork https://github.com/TheSecurityDev/heroku-buildpack-nodejs-pnpm.

Unfortunately this appears to not support [NodeJS runtime metrics](https://devcenter.heroku.com/articles/language-runtime-metrics-nodejs), which is why I came back to this issue. If I can figure out how to implement it, then it will be added to my fork.

**Comment by drush** [comment]
It is time to re-open this issue @joshwlewis

<img width="1327" alt="screenshot-pnpm vs yarn  npm trends-Safari-2023-09-13" src="https://github.com/heroku/heroku-buildpack-nodejs/assets/109985/0c29a0be-6be1-4593-b102-20496af6dc25">

**Comment by m4rvr** [comment]
It's time to move on and use a different hosting platform that actually cares about their users

**Comment by adamreisnz** [comment]
I reached this thread with hope in my heart, only to have it crushed and taken away when I reached the end of the thread.

**Comment by TheSecurityDev** [comment]
@adamreisnz @jose-fully-ported  Have you guys seen my comment above with my fork that supports PNPM? https://github.com/TheSecurityDev/heroku-buildpack-nodejs-pnpm

**Comment by TheSecurityDev** [comment]
> @TheSecurityDev mind opening a PR with the changes? That way maybe we can get the feature landed, assuming heroku is okay with it :)

I could try, but it's not necessary since you can just provide a custom URL to a Github repo to use a custom buildpack. Personally, I like to fork all the buildpacks I use anyway, so that if the Github repo is ever hacked or deleted it won't affect my server in the future since I have my own copy.

But really, mine was a fork of someone else's (that I made some improvements on) that wasn't forked from the official one. But then I merged the latest official buildpack into mine at some point, so I guess a pull request might be possible if I merge the latest changes again. But it's probably going to be pretty messy so I doubt a pull request would be accepted.

**Comment by TheSecurityDev** [comment]
> @TheSecurityDev any concerns on your end if I make the PR to this repo adding the functionality from your repo?

Nope, it's not even really my code anyway 😁

**Comment by kelsiesmurphy** [comment]
I would love to see this working. At the moment i'm using Vercel to host my nextjs application, but I would love to switch to Digital Ocean, which uses the heroku buildpack.

**Comment by renanleonel** [comment]
any news on this?

**Comment by colincasey** [comment]
Further discussion regarding `pnpm` support should move to [Heroku's public roadmap](https://github.com/heroku/roadmap) where it is being tracked: 
* https://github.com/heroku/roadmap/issues/268.

**Comment by JoeTheCookie217** [comment]
> @adamreisnz @jose-fully-ported Have you guys seen my comment above with my fork that supports PNPM? https://github.com/TheSecurityDev/heroku-buildpack-nodejs-pnpm

How do you use it in DigitalOcean?

**Comment by colincasey** [comment]
Good news! The `heroku/nodejs` buildpack will officially support [pnpm](https://pnpm.io/) soon 🎉  

For those looking to preview this in your application builds before it gets released, you can try it out today by swapping out the `heroku/nodejs` [buildpack](https://devcenter.heroku.com/articles/buildpacks) with one that references the [pnpm_support](https://github.com/heroku/heroku-buildpack-nodejs/tree/pnpm_support) branch:

```sh
heroku buildpacks:remove heroku/nodejs -a <your-appname>
heroku buildpacks:set https://github.com/heroku/heroku-buildpack-nodejs#pnpm_support -a <your-appname>
``` 

If you experience any build issues with [pnpm](https://pnpm.io/) during this preview phase, please file an [issue](https://github.com/heroku/heroku-buildpack-nodejs/issues) and we'll do our best to address it before #1224 is merged.

**Comment by edmorley** [comment]
pnpm support has now been merged and released 🎉 
https://devcenter.heroku.com/changelog-items/2879

If you had previously switched your app to using the `pnpm_support` branch using the GitHub buildpack URL above, you will need to remove the GitHub URL and switch back to the stable `heroku/nodejs` buildpack alias.

**Comment by olawalejuwonm** [comment]
> pnpm support has now been merged and released 🎉 https://devcenter.heroku.com/changelog-items/2879
> 
> If you had previously switched your app to using the `pnpm_support` branch using the GitHub buildpack URL above, you will need to remove the GitHub URL and switch back to the stable `heroku/nodejs` buildpack alias.

Great to see this

**Comment by NullVoxPopuli** [comment]
does the pnpm support automatically cache node_modules (recursively) when using a monorepo?
