### ISSUE TITLE
Wrong nodejs version

### ISSUE THREAD

**Issue by johncadengo** [heroku/heroku-buildpack-nodejs#929]
Using a pretty basic setup.

My `.buildpacks` file:

```
https://github.com/heroku/heroku-buildpack-nodejs.git#v183
```

My `package.json` file:

```
  "engines": {
    "node": "14.x"
  },
```

When I deploy to dokku, I see this:

```
-----> Installing binaries
       engines.node (package.json):  >= 0.10
       engines.npm (package.json):   unspecified (use default)
       engines.yarn (package.json):  unspecified (use default)
       
       Resolving node version >= 0.10...
       Downloading and installing node 16.4.0...
       Using default npm version: 7.18.1
       Resolving yarn version 1.22.x...
       Downloading and installing yarn (1.22.10)
       Installed yarn 1.22.10
```

I expect it to say `Downloading and installing node 14.x` instead.

What am I doing wrong?

**Comment by johncadengo** [comment]
Ok, I would just like to confirm what I'm trying here is correct.

If so, then I think what I was running into was my package.json file not being properly checked in to the git branch I was deploying. It will take me awhile to confirm it, but I want to make sure, these are the steps I need in order to set the nodejs version. Thanks!

**Comment by joshwlewis** [comment]
@johncadengo Yes, your `package.json` looks right. The engines declaration is what you need. The changes to `package.json` will certainly need to be checked in to `git`, otherwise those changes live only on your local machine and our build service can't see them. If you continue to have this issue, don't hesitate to open a support ticket at help.heroku.com.
